import CryptoKit
import Foundation
import KelidSettings
import PersianText

/// §6.5.3: turns raw pasteboard content into a `ClipDraft`, or decides to
/// skip it entirely. Pure logic — no `PasteboardClient`/database access —
/// so it's directly unit-testable.
public enum ClipClassifier {
    /// §6.5.3.1: pasteboard types that mean "don't capture this" when
    /// `skipSensitive` is on.
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// `^\s*[0-9۰-۹٠-٩]{4,8}\s*$` — a compile-time-constant literal that can
    /// only fail to parse from a programmer error, never a runtime
    /// condition (same reasoning as `LayoutRepository`'s bundled-fallback
    /// `fatalError`, rule 5.1.2).
    private static let otpRegex: NSRegularExpression = {
        guard let regex = try? NSRegularExpression(pattern: #"^\s*[0-9۰-۹٠-٩]{4,8}\s*$"#) else {
            fatalError("static OTP regex pattern failed to compile")
        }
        return regex
    }()

    public static func hasSensitiveType(_ typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains { identifier in
            sensitiveTypes.contains(identifier) || identifier.lowercased().contains("password")
        }
    }

    /// §6.5.3 steps 2–6, 8 for text/URL content. Image content is handled
    /// by `ClipboardService` separately (needs the actual image bytes and
    /// off-main-thread downsampling, §6.5.8). Returns `nil` when the
    /// content should be skipped entirely (empty, `ignorePatterns` match,
    /// or `otpHandling == .skip`).
    public static func classifyText(_ rawText: String, settings: ClipboardSettings, source: ClipSource, now: Date) -> ClipDraft? {
        let trimmed = rawText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        for pattern in settings.ignorePatterns {
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            let range = NSRange(rawText.startIndex ..< rawText.endIndex, in: rawText)
            if regex.firstMatch(in: rawText, range: range) != nil {
                return nil
            }
        }

        var text = rawText
        var isTruncated = false
        if text.count > 100_000 {
            text = String(text.prefix(100_000))
            isTruncated = true
        }

        var isSensitive = false
        var expiresAt: Date?

        if isOTP(trimmed) {
            switch settings.otpHandling {
            case .skip:
                return nil
            case .expire:
                isSensitive = true
                expiresAt = now.addingTimeInterval(120)
            case .keep:
                break
            }
        } else if settings.maskPasswordLike, isPasswordLike(trimmed) {
            isSensitive = true
            expiresAt = now.addingTimeInterval(600)
        }

        let kind: ClipKind = detectURL(text) != nil ? .url : .text
        let hash = sha256Hex(PersianNormalization.canonical(text))
        let searchKey = PersianNormalization.searchKey(text)

        return ClipDraft(
            kind: kind,
            text: text,
            searchKey: searchKey,
            contentHash: hash,
            charCount: text.count,
            isTruncated: isTruncated,
            isSensitive: isSensitive,
            expiresAt: expiresAt,
            source: source
        )
    }

    public static func draftForImage(hash: String, imageFile: String, thumbFile: String, source: ClipSource) -> ClipDraft {
        ClipDraft(kind: .image, imageFile: imageFile, thumbFile: thumbFile, contentHash: hash, source: source)
    }

    private static func isOTP(_ text: String) -> Bool {
        let range = NSRange(text.startIndex ..< text.endIndex, in: text)
        return otpRegex.firstMatch(in: text, range: range) != nil
    }

    /// §6.5.3.4: a single token of 8–64 characters, no spaces, with at
    /// least 3 of {lowercase, uppercase, digit, symbol}, and not a URL.
    private static func isPasswordLike(_ text: String) -> Bool {
        guard !text.contains(" "), (8 ... 64).contains(text.count) else { return false }
        guard detectURL(text) == nil else { return false }
        var hasLower = false, hasUpper = false, hasDigit = false, hasSymbol = false
        for scalar in text.unicodeScalars {
            if CharacterSet.lowercaseLetters.contains(scalar) {
                hasLower = true
            } else if CharacterSet.uppercaseLetters.contains(scalar) {
                hasUpper = true
            } else if CharacterSet.decimalDigits.contains(scalar) {
                hasDigit = true
            } else {
                hasSymbol = true
            }
        }
        return [hasLower, hasUpper, hasDigit, hasSymbol].filter(\.self).count >= 3
    }

    static func detectURL(_ text: String) -> URL? {
        guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) else { return nil }
        let range = NSRange(text.startIndex ..< text.endIndex, in: text)
        guard let match = detector.firstMatch(in: text, range: range), match.range == range else { return nil }
        return match.url
    }

    /// `public`: task 10.9's backup restore (`App/BackupService.swift`)
    /// needs to compute the exact same `contentHash` `classify(_:...)`
    /// would, so an imported clip correctly dedupes against (or matches) an
    /// existing one via `ClipRepository.upsert(_:)`'s own contentHash-based
    /// merge, rather than needing a separate uuid-based upsert path.
    public static func sha256Hex(_ text: String) -> String {
        sha256Hex(Data(text.utf8))
    }

    /// `public`: task 10.7's Share Extension needs to hash raw image data
    /// exactly as `ClipboardService.captureImage(data:)` already does, to
    /// dedupe a shared image against one already in the clip store.
    public static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
