@testable import ClipboardKit
import Foundation
import KelidSettings
import Testing

@Suite("ClipClassifier")
struct ClipClassifierTests {
    private let now = Date(timeIntervalSince1970: 1_000_000)

    @Test("concealed and transient pasteboard types are flagged as sensitive")
    func sensitiveTypesDetected() {
        #expect(ClipClassifier.hasSensitiveType(["org.nspasteboard.ConcealedType"]))
        #expect(ClipClassifier.hasSensitiveType(["org.nspasteboard.TransientType"]))
        #expect(ClipClassifier.hasSensitiveType(["org.nspasteboard.AutoGeneratedType"]))
        #expect(ClipClassifier.hasSensitiveType(["com.agilebits.onepassword"]))
        #expect(ClipClassifier.hasSensitiveType(["com.example.MyPasswordType"])) // case-insensitive "password" substring
        #expect(!ClipClassifier.hasSensitiveType(["public.utf8-plain-text"]))
    }

    @Test("empty or whitespace-only text is skipped")
    func emptyTextSkipped() {
        #expect(ClipClassifier.classifyText("", settings: ClipboardSettings(), source: .capture, now: now) == nil)
        #expect(ClipClassifier.classifyText("   \n\t  ", settings: ClipboardSettings(), source: .capture, now: now) == nil)
    }

    @Test("text longer than 100,000 characters is truncated and marked")
    func longTextIsTruncated() {
        let longText = String(repeating: "a", count: 100_050)
        let draft = ClipClassifier.classifyText(longText, settings: ClipboardSettings(), source: .capture, now: now)
        #expect(draft?.charCount == 100_000)
        #expect(draft?.isTruncated == true)
    }

    @Test("OTP-like text (Latin digits) with .expire handling is marked sensitive and expires in 120s")
    func otpLatinDigitsExpires() {
        var settings = ClipboardSettings()
        settings.otpHandling = .expire
        let draft = ClipClassifier.classifyText("123456", settings: settings, source: .capture, now: now)
        #expect(draft?.isSensitive == true)
        #expect(draft?.expiresAt == now.addingTimeInterval(120))
    }

    @Test("OTP-like text (Persian digits) is also detected")
    func otpPersianDigitsDetected() {
        var settings = ClipboardSettings()
        settings.otpHandling = .expire
        let draft = ClipClassifier.classifyText("۱۲۳۴۵۶", settings: settings, source: .capture, now: now)
        #expect(draft?.isSensitive == true)
    }

    @Test("OTP-like text (Arabic-Indic digits) is also detected")
    func otpArabicIndicDigitsDetected() {
        var settings = ClipboardSettings()
        settings.otpHandling = .expire
        let draft = ClipClassifier.classifyText("١٢٣٤٥٦", settings: settings, source: .capture, now: now)
        #expect(draft?.isSensitive == true)
    }

    @Test("otpHandling .skip drops the OTP entirely")
    func otpHandlingSkipDropsClip() {
        var settings = ClipboardSettings()
        settings.otpHandling = .skip
        #expect(ClipClassifier.classifyText("123456", settings: settings, source: .capture, now: now) == nil)
    }

    @Test("otpHandling .keep stores it normally, not sensitive")
    func otpHandlingKeepStoresNormally() {
        var settings = ClipboardSettings()
        settings.otpHandling = .keep
        let draft = ClipClassifier.classifyText("123456", settings: settings, source: .capture, now: now)
        #expect(draft?.isSensitive == false)
    }

    @Test("password-like text is masked and expires in 600s")
    func passwordLikeIsMasked() {
        let draft = ClipClassifier.classifyText("Xk9#mQ2pLz", settings: ClipboardSettings(), source: .capture, now: now)
        #expect(draft?.isSensitive == true)
        #expect(draft?.expiresAt == now.addingTimeInterval(600))
    }

    @Test("password-like detection requires at least 3 of 4 character classes")
    func passwordLikeRequiresThreeClasses() {
        // Only lowercase letters -> 1 class, not password-like even though length fits.
        let draft = ClipClassifier.classifyText("abcdefghij", settings: ClipboardSettings(), source: .capture, now: now)
        #expect(draft?.isSensitive == false)
    }

    @Test("maskPasswordLike = false disables password masking")
    func maskPasswordLikeSettingDisables() {
        var settings = ClipboardSettings()
        settings.maskPasswordLike = false
        let draft = ClipClassifier.classifyText("Xk9#mQ2pLz", settings: settings, source: .capture, now: now)
        #expect(draft?.isSensitive == false)
    }

    @Test("a URL is classified with kind .url")
    func urlIsClassified() {
        let draft = ClipClassifier.classifyText(
            "https://github.com/groue/GRDB.swift",
            settings: ClipboardSettings(),
            source: .capture,
            now: now
        )
        #expect(draft?.kind == .url)
    }

    @Test("plain text is classified with kind .text")
    func plainTextIsClassified() {
        let draft = ClipClassifier.classifyText("سلام دنیا", settings: ClipboardSettings(), source: .capture, now: now)
        #expect(draft?.kind == .text)
    }

    @Test("a URL is never treated as password-like, even if it fits the length/no-space shape")
    func urlNeverPasswordLike() {
        let draft = ClipClassifier.classifyText("https://a.co/Ab1$xyz", settings: ClipboardSettings(), source: .capture, now: now)
        #expect(draft?.isSensitive == false)
    }

    @Test("ignorePatterns matching the text drops the clip entirely")
    func ignorePatternsDropClip() {
        var settings = ClipboardSettings()
        settings.ignorePatterns = ["^SECRET-"]
        #expect(ClipClassifier.classifyText("SECRET-123", settings: settings, source: .capture, now: now) == nil)
        #expect(ClipClassifier.classifyText("not-secret", settings: settings, source: .capture, now: now) != nil)
    }

    @Test("identical text (after canonicalization) produces the same contentHash")
    func canonicalizationAffectsHash() {
        let a = ClipClassifier.classifyText("علي", settings: ClipboardSettings(), source: .capture, now: now)
        let b = ClipClassifier.classifyText("علی", settings: ClipboardSettings(), source: .capture, now: now)
        #expect(a?.contentHash == b?.contentHash)
    }
}
